# Generated by Django 5.0.4 on 2024-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_categorymodel_promotionduration_tagsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='uploads/brand'),
        ),
    ]
