# Generated by Django 5.0.4 on 2024-05-20 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_brandmodel_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivepromotions',
            name='duration',
        ),
        migrations.AddField(
            model_name='exclusivepromotions',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exclusivepromotions',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PromotionDuration',
        ),
    ]
