# Generated by Django 5.0.4 on 2024-06-03 12:38

import django.db.models.deletion
import django.utils.timezone
import e_store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('cate_image', models.ImageField(blank=True, upload_to='uploads/category')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PromotionDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_popular', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('brand_image', models.ImageField(blank=True, upload_to='uploads/brnad')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ManyToManyField(to='e_store.categorymodel')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('is_avalible', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='uploads/product')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('discount_percent', models.IntegerField(default=0, null=True)),
                ('category_trending', models.BooleanField(default=False)),
                ('warranty', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=5)),
                ('warranty_duration', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_store.brandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.categorymodel')),
                ('tags', models.ManyToManyField(to='e_store.tagsmodel')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImagegallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='uploads/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.productmodel')),
            ],
            options={
                'verbose_name': 'ProductImagegallery',
                'verbose_name_plural': 'Product Image gallery',
            },
        ),
        migrations.CreateModel(
            name='Productfeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(default='no information provided', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.productmodel')),
            ],
            options={
                'verbose_name': 'Productfeatures',
                'verbose_name_plural': 'Product features',
            },
        ),
        migrations.CreateModel(
            name='BanerAdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/Banneradd_background')),
                ('product_image', models.ImageField(upload_to='uploads/Banneradd_product', validators=[e_store.models.validate_image_extension])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/productdescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.productmodel')),
            ],
            options={
                'verbose_name': 'ProductPageDescription',
                'verbose_name_plural': 'Product Page Description',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='e_store.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusivePromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.productmodel')),
                ('duration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_store.promotionduration', verbose_name='duration')),
            ],
        ),
    ]
